<a href="https://colab.research.google.com/github/elhamod/BA820/blob/main/Text_Mining/Applications_Movie_Reviews_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Course: BA820 - Unsupervised and Unstructured ML**

**Notebook created by: Mohannad Elhamod**

In this notebook, you will work in the context of an online movie streaming service and analyze [IMDB's movie rating dataset](https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset/data). The goal is to understand how the movie ratings, summaries, and other metadata can be leveraged for business decisions.

You will explore how textual representations of book summaries can support tasks such as content recommendations and user preference analysis,

## Load The Data

In [1]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.1.4)

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "movies_metadata.csv"

# Load the latest version
df_movies = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rounakbanik/the-movies-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

# Set the path to the file you'd like to load
file_path = "credits.csv"

# Load the latest version
df_credits = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rounakbanik/the-movies-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

# Set the path to the file you'd like to load
file_path = "keywords.csv"

# Load the latest version
df_keywords = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rounakbanik/the-movies-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)


# Set the path to the file you'd like to load
file_path = "ratings_small.csv"

# Load the latest version
df_ratings = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rounakbanik/the-movies-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipython-input-3180211957.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_movies = kagglehub.load_dataset(

Using Colab cache for faster access to the 'the-movies-dataset' dataset.

/usr/local/lib/python3.12/dist-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(
/tmp/ipython-input-3180211957.py:24: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_credits = kagglehub.load_dataset(

Using Colab cache for faster access to the 'the-movies-dataset' dataset.

/tmp/ipython-input-3180211957.py:38: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_keywords = kagglehub.load_dataset(

Using Colab cache for faster access to the 'the-movies-dataset' dataset.

/tmp/ipython-input-3180211957.py:53: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_ratings = kagglehub.load_dataset(

Using Colab cache for faster access to the 'the-movies-dataset' dataset.

In [3]:
display(df_movies)
display(df_credits)
display(df_ratings)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

##EDA and Preprocessing

In [4]:
# drop adult movies
df_movies = df_movies[df_movies['adult'] == 'False']
# drop movies not released
df_movies = df_movies[df_movies['status'] == 'Released']
# keep only original langugae is English
df_movies = df_movies[df_movies['original_language'] == 'en']
# convert id and budget to int
df_movies['id'] = df_movies['id'].astype(int)
df_movies['budget'] = df_movies['budget'].astype(int)
# drop movies with low or unknown budget
df_movies = df_movies[df_movies['budget'] > 100000]
# drop movies where revenue or runtime is exactly zero (probably an error)
df_movies = df_movies[df_movies['revenue'] != 0.0]
df_movies = df_movies[df_movies['runtime'] != 0.0]
# drop nans
df_movies = df_movies.dropna(subset=["budget", "overview" , "popularity", "release_date", "title"])
# drop some columns
df_movies = df_movies.drop(columns=['adult', 'homepage', 'imdb_id', 'tagline', 'status', 'original_language' ,'spoken_languages', 'video', 'original_title', 'poster_path'])
#  add a column for whether a movie belongs to a collection
df_movies['belongs_to_collection'] = df_movies['belongs_to_collection'].notna()
# drop duplicates
df_movies = df_movies.drop_duplicates(subset=['id'])
# treat id as dataframe id
df_movies = df_movies.set_index('id')

df_movies

,belongs_to_collection,budget,genres,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,title,vote_average,vote_count
id,,,,,,,,,,,,,
862,True,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,Toy Story,7.7,5415.0
8844,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,Jumanji,6.9,2413.0
31357,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,Waiting to Exhale,6.1,34.0
949,False,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,187436818.0,170.0,Heat,7.7,1886.0
9091,False,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",International action superstar Jean Claude Van...,5.23158,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,64350171.0,106.0,Sudden Death,5.5,174.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
353491,False,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...","The last Gunslinger, Roland Deschain, has been...",50.903593,"[{'name': 'Imagine Entertainment', 'id': 23}, ...","[{'iso_3166_1': 'ZA', 'name': 'South Africa'},...",2017-08-03,71000000.0,95.0,The Dark Tower,5.7,688.0
378236,False,50000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...","Gene, a multi-expressional emoji, sets out on ...",33.694599,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-07-28,66913939.0,86.0,The Emoji Movie,5.8,327.0
395834,False,11000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",An FBI agent teams with the town's veteran gam...,40.796775,"[{'name': 'Thunder Road Pictures', 'id': 3528}...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2017-08-03,184770205.0,111.0,Wind River,7.4,181.0
62757,False,800000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","The sea, August, interesting and simple people...",0.903061,[],[],2006-11-23,1328612.0,100.0,Savages,5.8,6.0
63281,False,2000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...","У девушки Даши, приехавшей с подругой «покорят...",0.121844,"[{'name': 'Profit', 'id': 21163}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",2010-09-30,1268793.0,107.0,Pro Lyuboff,4.0,3.0

In [5]:
# remove from credits all movies not in df_movies
df_credits = df_credits[df_credits['id'].isin(df_movies.index)]
# drop nans
df_credits = df_credits.dropna()
# drop duplicates
df_credits = df_credits.drop_duplicates(subset=['id'])
# treat id as dataframe id
df_credits = df_credits.set_index('id')

df_credits

,cast,crew
id,,
862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
31357,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
949,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de..."
9091,"[{'cast_id': 1, 'character': 'Darren Francis T...","[{'credit_id': '52fe44dbc3a36847f80ae0f1', 'de..."
...,...,...
353491,"[{'cast_id': 9, 'character': 'Roland Deschain'...","[{'credit_id': '5912cf71c3a36864d40533b7', 'de..."
378236,"[{'cast_id': 2, 'character': 'Gene (voice)', '...","[{'credit_id': '5952d8f1c3a368151c025d0e', 'de..."
395834,"[{'cast_id': 9, 'character': 'Cory Lambert', '...","[{'credit_id': '572815d0c3a3687a00001314', 'de..."
62757,"[{'cast_id': 1001, 'character': 'Mister', 'cre...","[{'credit_id': '52fe468cc3a368484e096ba7', 'de..."
63281,"[{'cast_id': 1001, 'character': 'Vlad', 'credi...","[{'credit_id': '52fe46a3c3a368484e09b9fd', 'de..."

In [6]:
# remove from keywords and ratinds all movies not in df_movies
df_keywords = df_keywords[df_keywords['id'].isin(df_movies.index)]
df_ratings = df_ratings[df_ratings['movieId'].isin(df_movies.index)]
# drop nans
df_keywords = df_keywords.dropna()
df_ratings = df_ratings.dropna()
# drop duplicates
df_keywords = df_keywords.drop_duplicates(subset=['id'])
df_ratings = df_ratings.drop_duplicates()
# treat id as dataframe id
df_keywords = df_keywords.set_index('id')

display(df_keywords)
display(df_ratings)

                                                 keywords
id
862     [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
8844    [{'id': 10090, 'name': 'board game'}, {'id': 1...
31357   [{'id': 818, 'name': 'based on novel'}, {'id':...
949     [{'id': 642, 'name': 'robbery'}, {'id': 703, '...
9091    [{'id': 949, 'name': 'terrorist'}, {'id': 1562...
...                                                   ...
353491  [{'id': 75, 'name': 'gunslinger'}, {'id': 818,...
378236  [{'id': 207468, 'name': 'app'}, {'id': 229979,...
395834  [{'id': 570, 'name': 'rape'}, {'id': 1262, 'na...
62757                                                  []
63281                                                  []

[4697 rows x 1 columns]

       userId  movieId  rating   timestamp
10          1     1371     2.5  1260759135
13          1     2105     4.0  1260759139
16          1     2294     2.0  1260759108
26          2       62     3.0   835355749
29          2      150     5.0   835355395
...       ...      ...     ...         ...
99953     671     2959     4.0  1064890427
99956     671     3060     4.0  1063503947
99969     671     4011     4.0  1064245574
99983     671     4995     4.0  1064891537
99993     671     5902     3.5  1064245507

[20262 rows x 4 columns]

##**Questions**

### For each question, consider comparing the effectiveness of using a traditional NLP method vs. a deep-learning based approach (e.g., a pre-trained HuggingFace model)

## Q1. Does crafting more “exciting” movie overviews translate into higher audience ratings, and if so, how strong is that relationship?

## Q2. Your streaming platform wants to create recommendations based on user ratings. Using user–movie rating data, build and compare three recommendation approaches:

## 1. a baseline recommender that relies on raw user-movie ratings.
## 2. a recommender that extracts themes from user-movie ratings.

## Which recommender does better? Clearly explain how you measure improvement and why your chosen evaluation metric reflects business value.

## Q3. Your streaming platform wants to move beyond genre-only recommendations by incorporating a movie’s narrative setting—where and when the story takes place (e.g., “New York City, 1995”).

##Using user–movie rating data, build and compare three recommendation approaches:

## 2. a baseline recommender that relies on movie genre preferences only
## 3. a recommender that incorporates genres + narrative setting.

## Does adding setting information improve recommendation quality? Clearly explain how you measure improvement and why your chosen evaluation metric reflects business value.

## Important: “Setting” refers to where/when the movie events take place, not filming locations.

## Q4. Within the genre of *Action*, are there multiple distinct thematic sub-markets that behave differently in revenue and ratings? Answer this question based on both the movie overview and movie keywords.

##Q5. Movie titles often act as the first emotional signal to potential viewers, while the story itself conveys the deeper narrative tone. Does the sentiment conveyed by a movie’s title generally align with the sentiment conveyed by its story? How does the degree of the mismatch affect audience voting behavior?

##Q6. Studios often commit significant resources to sequels and franchise films. Do the movie title and story description help identify installments that are at higher risk of financial underperformance?