<a href="https://colab.research.google.com/github/elhamod/BA820/blob/main/Text_Mining/Book_Summaries_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Course: BA820 - Unsupervised and Unstructured ML**

**Notebook created by: Mohannad Elhamod**

In this notebook, you will work in the context of an online bookstore and analyze [a dataset of book plot summaries](https://huggingface.co/datasets/Iliasselyaa/CMUBookSummaryDataset). The goal is to understand how the content and attriubutes of a book can be leveraged for business decisions.

You will explore how textual representations of book summaries can support tasks such as content recommendations and reader preference analysis,

## Load The Data

In [ ]:
# !pip install datasets

In [ ]:
from datasets import load_dataset

# ds = load_dataset("textminr/cmu-book-summaries")
ds = load_dataset("Iliasselyaa/CMUBookSummaryDataset")

#get dataframe
df = ds["train"].to_pandas()

# drop all ids
df = df.drop(columns=["id", "wikipedia_id", "freebase_id"])



df

,title,author,publication_date,genres,summary
0,Animal Farm,George Orwell,1945-08-17,"Roman à clef, Satire, Children's literature, S...","Old Major, the old boar on the Manor Farm, ca..."
1,A Clockwork Orange,Anthony Burgess,1962,"Science Fiction, Novella, Speculative fiction,...","Alex, a teenager living in near-future Englan..."
2,The Plague,Albert Camus,1947,"Existentialism, Fiction, Absurdist fiction, Novel",The text of The Plague is divided into five p...
3,An Enquiry Concerning Human Understanding,David Hume,None,None,The argument of the Enquiry proceeds by a ser...
4,A Fire Upon the Deep,Vernor Vinge,None,"Hard science fiction, Science Fiction, Specula...",The novel posits that space around the Milky ...
...,...,...,...,...,...
16554,Under Wildwood,Colin Meloy,2012-09-25,None,"Prue McKeel, having rescued her brother from ..."
16555,Transfer of Power,Vince Flynn,2000-06-01,"Thriller, Fiction",The reader first meets Rapp while he is doing...
16556,Decoded,Jay-Z,2010-11-16,Autobiography,The book follows very rough chronological ord...
16557,America Again: Re-becoming The Greatness We Ne...,Stephen Colbert,2012-10-02,None,Colbert addresses topics including Wall Stree...
16558,Poor Folk,Fyodor Dostoyevsky,1846,"Epistolary novel, Speculative fiction",Makar Devushkin and Varvara Dobroselova are s...

##EDA and Preprocessing

In [ ]:
#remove Nans
df = df.dropna().reset_index(drop=True)

# extract year from publication_date as integer
df["publication_date"] = df["publication_date"].str[:4].astype(int)

# make genres as a list
df["genres"] = df["genres"].str.split(",")

display(df)

# get all unique genres with their counts
genres = df["genres"].explode().value_counts()

genres

,title,author,publication_date,genres,summary
0,Animal Farm,George Orwell,1945,"[Roman à clef, Satire, Children's literature...","Old Major, the old boar on the Manor Farm, ca..."
1,A Clockwork Orange,Anthony Burgess,1962,"[Science Fiction, Novella, Speculative ficti...","Alex, a teenager living in near-future Englan..."
2,The Plague,Albert Camus,1947,"[Existentialism, Fiction, Absurdist fiction,...",The text of The Plague is divided into five p...
3,All Quiet on the Western Front,Erich Maria Remarque,1929,"[War novel, Roman à clef]","The book tells the story of Paul Bäumer, a Ge..."
4,A Wizard of Earthsea,Ursula K. Le Guin,1968,"[Children's literature, Fantasy, Speculative...","Ged is a young boy on Gont, one of the larger..."
...,...,...,...,...,...
9288,The Third Lynx,Timothy Zahn,2007,[Science Fiction],The story starts with former government agent...
9289,Remote Control,Andy McNab,1997,"[Thriller, Fiction, Suspense]",The series follows the character of Nick Ston...
9290,Transfer of Power,Vince Flynn,2000,"[Thriller, Fiction]",The reader first meets Rapp while he is doing...
9291,Decoded,Jay-Z,2010,[Autobiography],The book follows very rough chronological ord...
9292,Poor Folk,Fyodor Dostoyevsky,1846,"[Epistolary novel, Speculative fiction]",Makar Devushkin and Varvara Dobroselova are s...

genres
 Fiction                 2962
 Speculative fiction     2197
Science Fiction          1755
 Fantasy                 1459
 Novel                   1354
                         ...
Mashup                      1
Alien invasion              1
 Dying Earth subgenre       1
Prose                       1
 Pastiche                   1
Name: count, Length: 328, dtype: int64

##**Questions**

###For each question, remember to enumerate the preprocessing steps you find necessary or best-suited to solve the business problem most effecticvely.

### Q1. You want to improve user engagement by helping customers discover books they may be interested in. When a user clicks on a specific book, the website aims to display a small list of *most similar books* based on content. Describe and build such a similarity-based recommendation system.

###Q2. Discuss how different text representation approaches (e.g.,  frequency-based representations, neural representations, etc.) can lead to different notions of similarity. Illustrate your answer using examples of popular books across different genres.

###Q3. Your store wants to organize its catalog into 10 distinct sections, where each section contains books that are similar to one another based on their content.  

*   What attributes would you use to represent each book so that similarity between books can be meaningfully assessed?
*   How would you interpret the resulting 10 sections in plain English?

###Q4. The store wants to help readers discover books they may not actively search for, but are still likely to enjoy. In particular, the platform aims to create a “You Might Have Missed” list that highlights books which share similar content and storytelling structure, even when they differ in genre or historical period. Discuss and design such a feature.

###Q5. Suppose a reader tells you they are not looking for a book similar to a single title, but one that *combines elements from multiple books*. Discuss and implement such a feature.

###Q6. The store wants to help users discover new authors. Suppose a user types a short, free-form description of what they feel like reading, for example:

> A fast-paced mystery with an investigator, lots of twists, and a dark tone.

###Implement a feature that returns the Top 5 authors most aligned with the user's interest.

In [ ]:
can ex

###Q7. The store wants to reorganize part of its catalog into 4 to 6 historical periods (e.g., early 20th century, mid-century, modern, etc.). For each period, the goal is to highlight genres that are particularly dominant or characteristic of that period, *relative to other periods*, rather than simply listing the most common genres overall. Discuss and implement such a feature.

###Q8. Could we build a model that predicts the genre(s) of a book based solely on its plot summary, so that genres can be automatically displayed when a customer clicks on a book?